apiVersion: v1
kind: Pod
metadata:
  name: dsc-project
  labels:
    name: dsc-project
spec:
  volumes:
  - name: nginx-logs
    emptyDir: {}

  containers:
  - name: nginx
    image: nginx-app:v1
    volumeMounts:
    - name: nginx-logs
      mountPath: /var/log/nginx

  - name: dsc-logger
    image: dsc:v1
    volumeMounts:
    - name: nginx-logs
      mountPath: /var/log/nginx
